[package]
name = "feminini-contract"
version = "0.1.0"
edition = "2024"

[dependencies]
soroban-sdk = "20.3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
soroban-sdk = { version = "20.3.0", features = ["testutils"] }
